# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Luke Murdock
tagline:          'A Jekyll Blog'
description:      'Luke's Blog'
url:              https://lukerex2k.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Luke Murdock'
  url:

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lukerex2k/lukerex2k
